# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(error_messages={'unique': 'Registration Number already used.'}, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('', '----'), ('1', 'Student'), ('2', 'Teaching Staff'), ('3', 'Employees')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
