# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_semester', models.DateField()),
                ('end_semester', models.DateField()),
            ],
        ),
    ]
