Feature: New Booking

Background:
    Given I run loaddata to populate dropdowns
    And I load a semester
    And I register the user "hugo@gmail.com" with the password "123456" and registration number "150016362" and engineering "Software" and category "Student"
    And I register an admin with email "lucas@gmail.com" and password "123456" and registration number "140016574" and category "Teaching Staff"
    And I register the booking "monitoria" with the building "UAC" with the place name "FGA-I1" and start_date "2018-10-20" and end_date "2018-10-30" of user "lucas@gmail.com"

Scenario: Sucessfull Booking creation
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I fill in "Booking Name:" with "Teste"
    And I choose "No"
    And I fill in "Start Date:" with "10/20/2019"
    And I fill in "End Date:" with "10/30/2019"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I click on an element with id of "button-confirm"
    Then I should see "Booking has been saved"

Scenario: End date greater then Start date
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I fill in "Booking Name:" with "Teste"
    And I choose "No"
    And I fill in "Start Date:" with "10/30/2019"
    And I fill in "End Date:" with "10/20/2019"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see "Invalid booking period: Booking must be in future dates"

Scenario: Booking already exists
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I fill in "Booking Name:" with "Teste"
    And I choose "No"
    And I fill in "Start Date:" with "10/20/2018"
    And I fill in "End Date:" with "10/30/2018"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see "Booking already exists"

Scenario: Empty booking name
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I choose "No"
    And I fill in "Start Date:" with "10/20/2018"
    And I fill in "End Date:" with "10/30/2018"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see an alert with text "Please fill out this field."

Scenario: Empty start date
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I choose "No"
    And I fill in "Booking Name:" with "Teste"
    And I fill in "End Date:" with "10/30/2018"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see an alert with text "Please fill out this field."

Scenario: Empty end date
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I choose "No"
    And I fill in "Booking Name:" with "Teste"
    And I fill in "Start Date:" with "10/30/2018"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see an alert with text "Please fill out this field."

Scenario: Empty start time
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I choose "No"
    And I fill in "Booking Name:" with "Teste"
    And I fill in "Start Date:" with "10/20/2018"
    And I fill in "End Date:" with "10/30/2018"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see an alert with text "Please select an item in the list."

Scenario: Empty end time
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I choose "No"
    And I fill in "Booking Name:" with "Teste"
    And I fill in "Start Date:" with "10/20/2018"
    And I fill in "End Date:" with "10/30/2018"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "22:00" from "Start Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see an alert with text "Please select an item in the list."

Scenario: Empty building
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I choose "No"
    And I fill in "Booking Name:" with "Teste"
    And I fill in "Start Date:" with "10/20/2018"
    And I fill in "End Date:" with "10/30/2018"
    And I select "22:00" from "Start Time:"
    And I select "00:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see an alert with text "Please select an item in the list."

 Scenario: Canceling a book
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I fill in "Booking Name:" with "Teste"
    And I choose "No"
    And I fill in "Start Date:" with "10/20/2019"
    And I fill in "End Date:" with "10/30/2019"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I click on an element with id of "button-cancel"
    Then I should see "Booking has been canceled"

 Scenario: Booking for a semester
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I fill in "Booking Name:" with "Teste"
    And I choose "Yes"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "22:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I click on an element with id of "button-confirm"
    Then I should see "Booking has been saved."

Scenario: End time equals start time
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I fill in "Booking Name:" with "Teste"
    And I choose "No"
    And I fill in "Start Date:" with "10/20/2019"
    And I fill in "End Date:" with "10/30/2019"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "20:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see "Invalid booking hours: End date must be greater then start date"

Scenario: End time lower then start time
    When I login in with email "lucas@gmail.com" and password "123456"
    Then I visit site page "/booking/newbooking/"
    And I fill in "Booking Name:" with "Teste"
    And I choose "No"
    And I fill in "Start Date:" with "10/20/2019"
    And I fill in "End Date:" with "10/30/2019"
    And I select "UAC" from "Building"
    And I select "UAC | FGA-I1" from "Place"
    And I select "20:00" from "Start Time:"
    And I select "18:00" from "End Time:"
    And I click on an element with id of "id_week_days_0"
    Then I press "Perform Booking"
    Then I should see "Invalid booking hours: End date must be greater then start date"
